# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    curl https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
    ./rustup-init
  displayName: 'Setup rust'
- script: |
    cargo build
  displayName: 'Build'
