# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  CARGO_HOME: '$(system.defaultWorkingDirectory)/.cargo'

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  displayName: 'Setup rust'
- script: |
    $CARGO_HOME/bin/cargo build
  displayName: 'Build'
